spring:
  application:
    name: HospitalReservation

  datasource:
    url: jdbc:mysql://localhost:3306/hospital_db # ??? ??? ??
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

logging:
  level:
    org:
      springframework:
        data:
          jpa: DEBUG
      hibernate: DEBUG

cors:
  allowed-origins: http://localhost:3000
